version: '3.8'

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    container_name: reservations
    command: pnpm run start:dev reservations
    ports:
      - '3001:3000'
    networks:
      - sleepr
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - HTTP_PORT=${RESERVATIONS_HTTP_PORT}
      - AUTH_HOST=${AUTH_HOST}
      - AUTH_PORT=${AUTH_TCP_PORT}

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    container_name: auth
    command: pnpm run start:dev auth
    ports:
      - '3002:3000'
    networks:
      - sleepr
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - HTTP_PORT=${AUTH_HTTP_PORT}
      - TCP_PORT=${AUTH_TCP_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

  mongo:
    image: docker.arvancloud.ir/mongo:6-jammy
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - sleepr
    volumes:
      - data:/data/db

  express:
    image: docker.arvancloud.ir/mongo-express
    container_name: express
    ports:
      - '8081:8081'
    networks:
      - sleepr
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass

volumes:
  data:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .

networks:
  sleepr:
